// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Saturn.Cli")>]
[<assembly: AssemblyProductAttribute("Saturn.Cli")>]
[<assembly: AssemblyDescriptionAttribute("A dotnet CLI tool for Saturn projects providing code generation and scaffolding.")>]
[<assembly: AssemblyVersionAttribute("1.0.2")>]
[<assembly: AssemblyFileVersionAttribute("1.0.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Saturn.Cli"
    let [<Literal>] AssemblyProduct = "Saturn.Cli"
    let [<Literal>] AssemblyDescription = "A dotnet CLI tool for Saturn projects providing code generation and scaffolding."
    let [<Literal>] AssemblyVersion = "1.0.2"
    let [<Literal>] AssemblyFileVersion = "1.0.2"
