// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Saturn.Dotnet")>]
[<assembly: AssemblyProductAttribute("Saturn.Dotnet")>]
[<assembly: AssemblyDescriptionAttribute("A dotnet CLI tool for Saturn projects")>]
[<assembly: AssemblyVersionAttribute("0.1.1")>]
[<assembly: AssemblyFileVersionAttribute("0.1.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Saturn.Dotnet"
    let [<Literal>] AssemblyProduct = "Saturn.Dotnet"
    let [<Literal>] AssemblyDescription = "A dotnet CLI tool for Saturn projects"
    let [<Literal>] AssemblyVersion = "0.1.1"
    let [<Literal>] AssemblyFileVersion = "0.1.1"
